#version
version: "1.0"

permalink: /:year/:month/:day/:title/

# 站点设置
title: "yddchsc"
email: 1145833162@qq.com
description: "the blog of yddchsc"
keywords: "yddchsc"

# 用户信息设置
weibo_username: yddchsc
github_username: yddchsc

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil



# 地址设置
baseurl: "/yddchsc.github.io"
url: "http://127.0.0.1:4000"


# 分页设置
paginate: 10
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

# duoshuo设置
duoshuo_shortname:yddchsc

# 百度统计设置
# baidu_analysis:
