#version
version: "1.0"

permalink: /:year/:month/:day/:title/

# 站点设置
title: "yddchsc"
email: 1145833162@qq.com
description: "the blog of yddchsc"
keywords: "yddchsc"

# 用户信息设置
weibo_username: yddchsc
github_username: yddchsc


# markdown: redcarpet

# redcarpet:
#   extensions:
#     - hard_wrap
#     - no_intra_emphasis
#     - autolink
#     - strikethrough
#     - fenced_code_blocks
#     - with_toc_data
#     - tables
#     - underline
#     - superscript

markdown: kramdown

kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  syntax_highlighter: rouge
  # auto_ids: true
  # footnote_nr: 1
  # entity_output: as_char
  # toc_levels: 1..6
  # parse_block_html: true
  coderay:
    coderay_line_numbers: nil
    # coderay_wrap: div
    # coderay_line_numbers: inline
    # coderay_line_numbers_start: 1
    # coderay_tab_width: 4
    # coderay_bold_every: 10
    # coderay_css: style

# 地址设置
baseurl: "/yddchsc.github.io"
url: "http://yddchsc.github.io"


# 分页设置
paginate: 10
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

# duoshuo设置
duoshuo_shortname: yddchsc

# 百度统计设置
# baidu_analysis:
